--- 
- name: Install Docker and Docker-Compose
  hosts: all
  become: yes
  gather_facts: False
  tasks:
  - name: Install Docker
    ansible.builtin.yum:
      name: docker
      update_cache: yes
      state: present
  - name: Install Docker-Compose
    ansible.builtin.get_url:
      url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: +x
  - name: Check Docker-Compose version 
    ansible.builtin.command: docker-compose version
    register: docker_compose_version
  - ansible.builtin.debug: msg={{ docker_compose_version.stdout_lines }}
  - name: Start Docker Daemon
    ansible.builtin.systemd:
      name: docker
      state: started
      enabled: yes

- name: Add user to docker group 
  hosts: all
  become: yes
  tasks:
  - name: Add ec2-user to docker group 
    ansible.builtin.user:
      name: ec2-user
      groups: docker
      append: yes
  - name: Reconnect to server session
    ansible.builtin.meta: reset_connection